---
title: "Extracting Volve data. Step by step"
output: html_notebook
---


```{r}
# read the Eclipse report
volve_2016_prt <- "VOLVE_2016.PRT"

volve_2016_txt <- readLines(volve_2016_prt)
```


```{r}
# get the rows that have the words "BALANCE  AT"
balance_rows <- grep("^.*BALANCE  AT", volve_2016_txt)
head(balance_rows, 50)
```

```{r}
# show samples of text read
volve_2016_txt[balance_rows[1]]
volve_2016_txt[balance_rows[2]]
volve_2016_txt[balance_rows[3]]
```

```{r}
# extract the number of days from a line of text
sub(".*?(\\d+.\\d.)+.*", "\\1", volve_2016_txt[balance_rows[3]])
```


```{r}
# get a list of rows from "BALANCE  AT" for 22 more rows ahead

# find the rows where we find the word "BALANCE  AT"
balance_rows <- grep("^.*BALANCE  AT", volve_2016_txt)

# add rows ahead to where the word BALANCE AT was found
field_totals_range <- lapply(seq_along(balance_rows), function(x) 
    c(balance_rows[x], balance_rows[x]+1:21))

field_totals_range[[1]]   # for report page 1 only
```

```{r}
# print text report page #1 from range of rows
# [[1]] is  0.00  DAYS, REPORT   0
field_totals_txt_1 <- volve_2016_txt[field_totals_range[[1]]]
field_totals_txt_1
```


```{r}
# get the days from the fourth report page
# get first row of list element 4 (first row of report 4-1)
sub(".*?(\\d+.\\d.)+.*", "\\1", volve_2016_txt[field_totals_range[[4]][1]])
```

```{r}
# get only the first row indices of the Field Totals report
days_rows <- sapply(seq_along(field_totals_range), function(x) field_totals_range[[x]][1])
head(days_rows, 50)
```

```{r}
# extract the number of days as numeric
as.numeric(unlist(lapply(seq_along(days_rows), function(x) {
    sub(".*?(\\d+.\\d.)+.*", "\\1", volve_2016_txt[days_rows[x]])
})))
```


    date_value <- sub(".*?(\\d{1,2} [A-Z]{3} \\d{4})+.*", "\\1", page[date_row_txt])
    
```{r}
# get the text from all pages and put them in a list
# one list item per page. Example [[1]] page 1; [[2]] for page 2; [[3]] for page 3
# and so on
report_by_page <- lapply(seq_along(field_totals_range), function(x) 
    volve_2016_txt[field_totals_range[[x]]])

report_by_page[[1]][1:5]  # get only the first 5 rows of the page 1
```

```{r}
# get the dates from each report page
date_dfs <- lapply(seq_along(report_by_page), function(x) {
    page <- report_by_page[[x]]
    date_row_txt <- grep("^.*REPORT", page)
    date_value <- sub(".*?(\\d{1,2} [A-Z]{3} \\d{4})+.*", "\\1", page[date_row_txt])
    data.frame(date = date_value, stringsAsFactors = FALSE)
})

date_df <- do.call("rbind", date_dfs)
date_df
```

```{r rows.print=25}
# get the oil currently in place (CIP) from each report page
cip_dfs <- lapply(seq_along(report_by_page), function(x) {
    page <- report_by_page[[x]]
    cip_row_txt <- grep("^.*:CURRENTLY IN PLACE", page)     # key text to detect
    cip_value <- sub(".*?(\\d+.)+.*", "\\1", page[cip_row_txt]) # extract value
    data.frame(CIP_m3 = cip_value, stringsAsFactors = FALSE)
})

cip_df <- do.call("rbind", cip_dfs)
cip_df
```
    
    
