---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)

# read the Eclipse report
# read the Eclipse report
proj_root <- rprojroot::find_rstudio_root_file()
volve_2016_prt <- file.path(proj_root, "inst/rawdata", "VOLVE_2016.PRT")

volve_2016_txt <- readLines(volve_2016_prt)
```


```{r}
# get a list of rows from "BALANCE  AT" for 22 more rows ahead

# find the rows where we find the word "BALANCE  AT"
balance_rows <- grep("^.*BALANCE  AT", volve_2016_txt)

# add rows ahead to where the word BALANCE AT was found
field_totals_range <- lapply(seq_along(balance_rows), function(x) 
    c(balance_rows[x], balance_rows[x]+1:21))

field_totals_range[[1]]   # sample for report page 1 only
```


## Iteration through the FIELD TOTALS report pages


```{r rows.print=25}
# try different strategy
# iterating through the report pages in FIELD TOTALS
# get:
#    days, oil currently in place, oil originally in place, 
#    oil outflow through wells

# get the text from all pages and put them in a list
list_of_report_txt_pages <- lapply(seq_along(field_totals_range), function(x) 
    volve_2016_txt[field_totals_range[[x]]])

# iterate through the list of pages
tab <- lapply(seq_along(list_of_report_txt_pages), function(x) {
    page <- list_of_report_txt_pages[[x]]  # put all pages text in a list
    days_row_txt <- page[1] # get 1st row of page
    days_value <- sub(".*?(\\d+.\\d.)+.*", "\\1", days_row_txt) # extract the days
    # get the date
    date_row_txt <- grep("^.*REPORT", page)
    date_value <- sub(".*?(\\d{1,2} [A-Z]{3} \\d{4})+.*", "\\1", page[date_row_txt])
    # get oil currently in place
    cip_row_txt <- grep("^.*:CURRENTLY IN PLACE", page)
    cip_value <- sub(".*?(\\d+.)+.*", "\\1", page[cip_row_txt])
    # get OOIP
    ooip_row_txt <- grep("^.*:ORIGINALLY IN PLACE", page)
    ooip_value <- sub(".*?(\\d+.)+.*", "\\1", page[ooip_row_txt])
    # get total fluid outflow through wells
    otw_row_txt <- grep("^.*:OUTFLOW THROUGH WELLS", page) # row index at this line
    otw_group_pattern <- ".*?(\\d+.)+.*?(\\d+.)+.*?(\\d+.)+.*"  # groups
    oil_otw_value <- sub(otw_group_pattern, "\\1", page[otw_row_txt]) # get oil outflow
    wat_otw_value <- sub(otw_group_pattern, "\\2", page[otw_row_txt]) # get gas outflow
    gas_otw_value <- sub(otw_group_pattern, "\\3", page[otw_row_txt]) # get water
    # get pressure
    pav_row_txt <- grep("PAV =", page)
    pav_value <- sub(".*?(\\d+.\\d.)+.*", "\\1", page[pav_row_txt])
    # dataframe
    data.frame(date = date_value, days = days_value, cip = cip_value, ooip =  ooip_value,
               oil_otw = oil_otw_value,
               wat_otw = wat_otw_value,
               gas_otw = gas_otw_value, 
               pav = pav_value) # , sample = page[date_row_txt]
})

tbl <- do.call("rbind", tab)
tbl
```


```{r}
# grep doesn't do anything here
grep(".*?(\\d{2} [A-Z]{3} \\d{4})+.*", "REPORT   0    31 DEC 2007   *  RUN                   ", value = TRUE)
```


```{r}
# extract the date
sub(".*?(\\d{2} [A-Z]{3} \\d{4})+.*", "\\1", 
    "REPORT   0    31 DEC 2007   *  RUN                             ")
```


```{r}
# extract the pressure
sub(".*?(\\d+.\\d.)+.*", "\\1", "   :     PAV =        329.61  BARSA             :")
```


```{r}
sub(".*?(\\d+.\\d.)+.*", "\\1", volve_2016_txt[field_totals_range[[4]][1]])
```



```{r}
# # extract the oil currently in place
# currently_in_place_rows  <- grep("^.*:CURRENTLY IN PLACE", volve_2016_txt)
# originally_in_place_rows <- grep("^.*:ORIGINALLY IN PLACE", volve_2016_txt)
# head(currently_in_place_rows)
# head(originally_in_place_rows)
```

```{r}
# grep(".*?(\\d+.)+.*", volve_2016_txt[currently_in_place_rows[5]], value= TRUE)
# sub(".*?(\\d+.)+.*", "\\1", volve_2016_txt[currently_in_place_rows[5]])
sub(".*?(\\d+.)+.*", "\\1", volve_2016_txt[originally_in_place_rows[5]])
```

